//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class example {
  public static SWIGTYPE_p_mjModel mj_loadXML(string filename, SWIGTYPE_p_mjVFS vfs, string error, int error_sz) {
    global::System.IntPtr cPtr = examplePINVOKE.mj_loadXML(filename, SWIGTYPE_p_mjVFS.getCPtr(vfs), error, error_sz);
    SWIGTYPE_p_mjModel ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_mjModel(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_mjData mj_makeData(SWIGTYPE_p_mjModel m) {
    global::System.IntPtr cPtr = examplePINVOKE.mj_makeData(SWIGTYPE_p_mjModel.getCPtr(m));
    SWIGTYPE_p_mjData ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_mjData(cPtr, false);
    return ret;
  }

  public static void mj_step(SWIGTYPE_p_mjModel m, SWIGTYPE_p_mjData d) {
    examplePINVOKE.mj_step(SWIGTYPE_p_mjModel.getCPtr(m), SWIGTYPE_p_mjData.getCPtr(d));
  }

  public static void mj_deleteData(SWIGTYPE_p_mjData d) {
    examplePINVOKE.mj_deleteData(SWIGTYPE_p_mjData.getCPtr(d));
  }

  public static void mj_deleteModel(SWIGTYPE_p_mjModel m) {
    examplePINVOKE.mj_deleteModel(SWIGTYPE_p_mjModel.getCPtr(m));
  }

}
